backend:
  name: github
  repo: Anthonytr/caitlin-gibson # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "source/images" # Folder where user uploaded files should go
public_folder: "images" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "pages" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Pages" # Used in the UI, ie.: "New Post"
    files:
      - file: "data/home.yml"
        label: "Homepage"
        name: "homepage"
        fields: # The fields each document in this collection have
          - {label: "First Name", name: "first_name", widget: "string"}
          - {label: "Last Name", name: "last_name", widget: "string"}
          - {label: "Position", name: "position", widget: "string"}
          - {label: "Jersey", name: "jersey", widget: "number"}
          - {label: "Club", name: "club", widget: "string"}
          - {label: "Coach", name: "coach", widget: "string"}
          - {label: "High School", name: "school", widget: "string"}
          - {label: "G.P.A.", name: "gpa", widget: "number"}
          - {label: "Assessment", name: "coach_assessment", widget: "text"}
          - {label: "Background Image", name: "background_url", widget: "image"}